modLoader="javafml"
loaderVersion="[4,)"
license="Not specified"

[[mods]]
modId="loggy_doors"
version="1.0.0"
displayName="Log Door Mod"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="SaishoVibes"
description="Adds all log doors, and stripped variants to make fun hidden areas"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.loggy_doors]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.65,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.loggy_doors]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration